site_name: COMP423 Course Notes
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - fenced_code
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg